// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtYHlAkZPBCZ4ZceTM64FHtcnV6iPfkjY',
    appId: '1:257155343613:web:0cd081013152c2a0d14a94',
    messagingSenderId: '257155343613',
    projectId: 'synq-1620e',
    authDomain: 'synq-1620e.firebaseapp.com',
    storageBucket: 'synq-1620e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkY4RWtROj_-07sLZF2Ns4PN7xmft5Xtg',
    appId: '1:257155343613:android:fe615f5330ba7099d14a94',
    messagingSenderId: '257155343613',
    projectId: 'synq-1620e',
    storageBucket: 'synq-1620e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoz09QDKiImQaQE32tFOPMOhgURxWZeE',
    appId: '1:257155343613:ios:88d9839ad1aaf009d14a94',
    messagingSenderId: '257155343613',
    projectId: 'synq-1620e',
    storageBucket: 'synq-1620e.firebasestorage.app',
    iosBundleId: 'com.example.synqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoz09QDKiImQaQE32tFOPMOhgURxWZeE',
    appId: '1:257155343613:ios:88d9839ad1aaf009d14a94',
    messagingSenderId: '257155343613',
    projectId: 'synq-1620e',
    storageBucket: 'synq-1620e.firebasestorage.app',
    iosBundleId: 'com.example.synqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtYHlAkZPBCZ4ZceTM64FHtcnV6iPfkjY',
    appId: '1:257155343613:web:b60d0a8fac92385cd14a94',
    messagingSenderId: '257155343613',
    projectId: 'synq-1620e',
    authDomain: 'synq-1620e.firebaseapp.com',
    storageBucket: 'synq-1620e.firebasestorage.app',
  );
}
